name: Check Code completeness

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:
    outputs:
      check_lint_output:
        description: Output for lint and format checking
        value: ${{ jobs.check_lint.outputs.job_output1 }}  

jobs:
  check_lint:
    runs-on: ubuntu-latest
    strategy:
            matrix:
                node_version: [16.10.x]

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
            node-version: ${{matrix.node_version}}

      # Install dependencies
      - name: install dependencies
        run: npm install

      # Check code format
      - name: Check code format
        run: npm run format:check  

      # Check code lint
      - name: check code lint
        run: npm run lint