name: Deploy to Production

on: [workflow_dispatch]

jobs:
  check-lint:
    uses: kaustav1808/sellify_web/.github/workflows/check-lint.yml@master

  deploy:
    runs-on: ubuntu-latest
    needs: [check-lint]
    if: ${{ github.ref == 'refs/heads/master' }}
    
    steps:
      - name: Deploying to Production
        run: echo deploying  