name: Deploy to Production

on: [workflow_dispatch]

jobs:
  check-lint:
    uses: kaustav1808/sellify_web/.github/workflows/check-lint.yml@master

  deploy:
    runs-on: ubuntu-latest
    needs: [check-lint]
    env:
      NEXT_PUBLIC_CLIENT_URL: ${{secrets.PROD_CLIENT_URL}}
    if: ${{ github.ref == 'refs/heads/master' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: build frontend code
        run: |
          npm run build    
          npm run export    

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Copy files to the production bucket with the AWS CLI
        run: |
          aws s3 rm --recursive s3://${{secrets.PRODUCTION_BUCKET}}
          aws s3 sync ./out/ s3://${{secrets.PRODUCTION_BUCKET}}
          aws cloudfront create-invalidation --distribution-id ${{secrets.PROD_CLOUDFRONT_DISTRIBUTION}} --paths "/*"    