name: Check Code completeness

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check code format
      - name: Check code format
        run: npm run format:check

      # Check code format
      - name: Check code format
        run: npm run lint